### ISSUE TITLE
Cannot run ros2 cfe_plugin (unable to open database file)

### ISSUE THREAD

**Issue by ivanperez-keera** [traclabs/brash#4]
Hi,

I followed your instructions and I'm stuck at the following step:

```
# ros2 launch cfe_plugin cfe_bridge.launch.py
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-03-05-02-22-42-167031-a9f2dd154f8b-178
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [fsw_ros2_bridge-1]: process started with pid [179]
[fsw_ros2_bridge-1] [INFO] [1709605362.475708575] [cfe_bridge]: namespace: /groundsystem
[fsw_ros2_bridge-1] [WARN] [1709605362.476229264] [cfe_bridge]: ================================================================
[fsw_ros2_bridge-1] [WARN] [1709605362.476871856] [cfe_bridge]: Using FSW Plugin: cfe_plugin.cfe_plugin
[fsw_ros2_bridge-1] [WARN] [1709605362.477509724] [cfe_bridge]: ================================================================
[fsw_ros2_bridge-1] [INFO] [1709605362.492146442] [cfe_bridge]: Setting up cFE plugin
[fsw_ros2_bridge-1] [ERROR] [1709605362.493667710] [cfe_bridge]: unable to open database file
[fsw_ros2_bridge-1] Traceback (most recent call last):
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/install/fsw_ros2_bridge/lib/fsw_ros2_bridge/fsw_ros2_bridge", line 33, in <module>
[fsw_ros2_bridge-1]     sys.exit(load_entry_point('fsw-ros2-bridge', 'console_scripts', 'fsw_ros2_bridge')())
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/fsw_ros2_bridge/fsw_ros2_bridge/fsw_ros2_bridge.py", line 419, in main
[fsw_ros2_bridge-1]     bridge = FSWBridge()
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/fsw_ros2_bridge/fsw_ros2_bridge/fsw_ros2_bridge.py", line 72, in __init__
[fsw_ros2_bridge-1]     self._fsw = fsw_ros2_bridge.fsw_wrapper.FSWWrapper(self, self._plugin_name)
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/fsw_ros2_bridge/fsw_ros2_bridge/fsw_wrapper.py", line 37, in __init__
[fsw_ros2_bridge-1]     self._plugin = importlib.import_module(plugin, ".").FSWPlugin(node)
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/install/cfe_plugin/local/lib/python3.10/dist-packages/cfe_plugin/cfe_plugin.py", line 85, in __init__
[fsw_ros2_bridge-1]     self._juicer_interface = JuicerInterface(self._node, resource_path)
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/juicer_util/juicer_util/juicer_interface.py", line 118, in __init__
[fsw_ros2_bridge-1]     self._db_data.load_data()
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/juicer_util/juicer_util/juicer_database.py", line 167, in load_data
[fsw_ros2_bridge-1]     self.retrieve_all_symbols()
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/juicer_util/juicer_util/juicer_database.py", line 102, in retrieve_all_symbols
[fsw_ros2_bridge-1]     cur = self._conn.cursor()
[fsw_ros2_bridge-1] AttributeError: 'NoneType' object has no attribute 'cursor'
[ERROR] [fsw_ros2_bridge-1]: process has died [pid 179, exit code 1, cmd '/root/code/humble_ws/brash/install/fsw_ros2_bridge/lib/fsw_ros2_bridge/fsw_ros2_bridge --ros-args -r __node:=cfe_bridge --params-file /root/code/humble_ws/brash/install/cfe_plugin/share/cfe_plugin/config/cfe_config.yaml --params-file /root/code/humble_ws/brash/install/juicer_util/share/juicer_util/config/cfe_plugin_config.yaml'].
```

It's not finding a resource DB file.

I looked into that file `/root/code/humble_ws/brash/install/juicer_util/share/juicer_util/config/cfe_plugin_config.yaml` and that's pointing to `/code/juicer/dbs/rover_all.sqlite`, which does not exist on my machine. I replaced that with:
```
juicer_db: ["cfs_bootes-rc1-dev83_TL.sqlite"]
```

which is commented out, and that now gives the following error message:
```
# ros2 launch cfe_plugin cfe_bridge.launch.py
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-03-05-02-28-39-415307-a9f2dd154f8b-255
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [fsw_ros2_bridge-1]: process started with pid [256]
[fsw_ros2_bridge-1] [INFO] [1709605719.717171105] [cfe_bridge]: namespace: /groundsystem
[fsw_ros2_bridge-1] [WARN] [1709605719.717957443] [cfe_bridge]: ================================================================
[fsw_ros2_bridge-1] [WARN] [1709605719.718812926] [cfe_bridge]: Using FSW Plugin: cfe_plugin.cfe_plugin
[fsw_ros2_bridge-1] [WARN] [1709605719.719615389] [cfe_bridge]: ================================================================
[fsw_ros2_bridge-1] [INFO] [1709605719.734542639] [cfe_bridge]: Setting up cFE plugin
[fsw_ros2_bridge-1] [WARN] [1709605719.800479014] [cfe_bridge]: Can't replace CFE_ES_CDS_AccessCacheData with CFE_ES_CDS_AccessCache
[fsw_ros2_bridge-1] [WARN] [1709605719.801292800] [cfe_bridge]: wrong size 72 vs 96
[fsw_ros2_bridge-1] [WARN] [1709605719.802574079] [cfe_bridge]: Can't replace CFE_ES_CDS_AccessCacheData with CFE_ES_CDS_AccessCache
[fsw_ros2_bridge-1] [WARN] [1709605719.803416619] [cfe_bridge]: wrong size 72 vs 96
[fsw_ros2_bridge-1] [WARN] [1709605719.858431706] [cfe_bridge]: Can't replace CFE_SB_MsgMapFileEntry_t with CFE_SB_Msg
[fsw_ros2_bridge-1] [WARN] [1709605719.859315646] [cfe_bridge]: wrong size 8 vs 16
[fsw_ros2_bridge-1] [WARN] [1709605720.011126237] [cfe_bridge]: Can't replace CF_ChunkIdx_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709605720.011710440] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709605720.012781424] [cfe_bridge]: Can't replace CF_ChunkIdx_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709605720.013424452] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709605720.014561610] [cfe_bridge]: Can't replace CF_ChunkOffset_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709605720.015237091] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709605720.016319571] [cfe_bridge]: Can't replace CF_ChunkOffset_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709605720.016983554] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709605720.018082243] [cfe_bridge]: Can't replace CF_ChunkSize_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709605720.018559024] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709605720.019607382] [cfe_bridge]: Can't replace CF_ChunkSize_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709605720.020171933] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709605720.021654527] [cfe_bridge]: Can't replace CF_ChunkList_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709605720.022271872] [cfe_bridge]: wrong size 16 vs 8
[fsw_ros2_bridge-1] [WARN] [1709605720.026607963] [cfe_bridge]: Can't replace CF_Logical_TlvData with CF_Logical_Tlv
[fsw_ros2_bridge-1] [WARN] [1709605720.027123468] [cfe_bridge]: wrong size 8 vs 16
[fsw_ros2_bridge-1] [WARN] [1709605720.028183446] [cfe_bridge]: Can't replace CF_Logical_TlvData with CF_Logical_Tlv
[fsw_ros2_bridge-1] [WARN] [1709605720.028671852] [cfe_bridge]: wrong size 8 vs 16
[fsw_ros2_bridge-1] [WARN] [1709605720.031324031] [cfe_bridge]: Can't replace CF_Logical_TlvList_t with CF_Logical_Tlv
[fsw_ros2_bridge-1] [WARN] [1709605720.031879320] [cfe_bridge]: wrong size 72 vs 16
[fsw_ros2_bridge-1] [WARN] [1709605720.043172983] [cfe_bridge]: Can't replace CF_ChunkWrapper_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709605720.043921969] [cfe_bridge]: wrong size 32 vs 8
[fsw_ros2_bridge-1] [WARN] [1709605720.069910381] [cfe_bridge]: Can't replace CF_PlaybackDirCmd_t with CF_Playback
[fsw_ros2_bridge-1] [WARN] [1709605720.070577828] [cfe_bridge]: wrong size 144 vs 148
[fsw_ros2_bridge-1] [WARN] [1709605720.071688405] [cfe_bridge]: Can't replace CF_PlaybackDirCmd_t with CF_Playback
[fsw_ros2_bridge-1] [WARN] [1709605720.072354332] [cfe_bridge]: wrong size 144 vs 148
[fsw_ros2_bridge-1] [WARN] [1709605720.073435013] [cfe_bridge]: Can't replace CF_TransactionCmd_t with CF_Transaction
[fsw_ros2_bridge-1] [WARN] [1709605720.074053652] [cfe_bridge]: wrong size 20 vs 136
[fsw_ros2_bridge-1] [INFO] [1709605720.084746987] [cfe_bridge]: udp_receive_port: 1235
[fsw_ros2_bridge-1] [INFO] [1709605720.085414408] [cfe_bridge]: udp_send_port: 1234
[fsw_ros2_bridge-1] [INFO] [1709605720.086111208] [cfe_bridge]: udp_telemetry_ip: 0.0.0.0
[fsw_ros2_bridge-1] [INFO] [1709605720.086879003] [cfe_bridge]: udp_command_ip: 127.0.0.1
[fsw_ros2_bridge-1] [INFO] [1709605720.087568533] [cfe_bridge]: parsing cFE config file...
[fsw_ros2_bridge-1] [INFO] [1709605720.160410117] [cfe_bridge]: commands:
[fsw_ros2_bridge-1] [INFO] [1709605720.161651590] [cfe_bridge]: telemetry:
[fsw_ros2_bridge-1] [INFO] [1709605720.162493140] [cfe_bridge]: starting timer thread to receive CFS telemetry
[fsw_ros2_bridge-1] [WARN] [1709605720.163343021] [cfe_bridge]: cmd with msg_size=0 (dynamic)
[fsw_ros2_bridge-1] [WARN] [1709605720.163925138] [cfe_bridge]: cmd with msg_size=0 (dynamic)
[fsw_ros2_bridge-1] Traceback (most recent call last):
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/install/fsw_ros2_bridge/lib/fsw_ros2_bridge/fsw_ros2_bridge", line 33, in <module>
[fsw_ros2_bridge-1]     sys.exit(load_entry_point('fsw-ros2-bridge', 'console_scripts', 'fsw_ros2_bridge')())
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/fsw_ros2_bridge/fsw_ros2_bridge/fsw_ros2_bridge.py", line 419, in main
[fsw_ros2_bridge-1]     bridge = FSWBridge()
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/fsw_ros2_bridge/fsw_ros2_bridge/fsw_ros2_bridge.py", line 72, in __init__
[fsw_ros2_bridge-1]     self._fsw = fsw_ros2_bridge.fsw_wrapper.FSWWrapper(self, self._plugin_name)
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/fsw_ros2_bridge/fsw_ros2_bridge/fsw_wrapper.py", line 37, in __init__
[fsw_ros2_bridge-1]     self._plugin = importlib.import_module(plugin, ".").FSWPlugin(node)
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/install/cfe_plugin/local/lib/python3.10/dist-packages/cfe_plugin/cfe_plugin.py", line 152, in __init__
[fsw_ros2_bridge-1]     msg_size = symbol_name_map[ci.get_msg_type()].get_size()
[fsw_ros2_bridge-1] KeyError: 'RoverAppTwistCmdt'
[ERROR] [fsw_ros2_bridge-1]: process has died [pid 256, exit code 1, cmd '/root/code/humble_ws/brash/install/fsw_ros2_bridge/lib/fsw_ros2_bridge/fsw_ros2_bridge --ros-args -r __node:=cfe_bridge --params-file /root/code/humble_ws/brash/install/cfe_plugin/share/cfe_plugin/config/cfe_config.yaml --params-file /root/code/humble_ws/brash/install/juicer_util/share/juicer_util/config/cfe_plugin_config.yaml'].
```

What needs to happen? Is there a valid sqlite file that can be used just to test the bridge?

**Comment by ivanperez-keera** [comment]
I tried to use juicer to generate a valid file, and I'm encountering this:

```
# mkdir -p /root/code/juicer/dbs
# # ros2 launch juicer_util generate_juicer_database.launch.py
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-03-05-02-49-45-743119-000eb8a29f9e-143
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [generate_juicer_database-1]: process started with pid [144]
[generate_juicer_database-1] [INFO] [1709606985.929708572] [create_message_database]: CreateMessageDatabase() application to parse binaries and output an SQL Database with message structure information
[generate_juicer_database-1] [INFO] [1709606985.930829744] [create_message_database]: cfs_path: /root/code/cFS
[generate_juicer_database-1] [INFO] [1709606985.931253597] [create_message_database]: juicer_path: /root/code/juicer
[generate_juicer_database-1] [INFO] [1709606985.931716458] [create_message_database]: output: combined.sqlite
[generate_juicer_database-1] [INFO] [1709606985.932149958] [create_message_database]: files: ['core-cpu1', 'cf/cfe_assert.so', 'cf/ci_lab.so', 'cf/ros_app.so', 'cf/sample_app.so', 'cf/sample_lib.so', 'cf/sbn_f_remap.so', 'cf/sbn.so', 'cf/sbn_udp.so', 'cf/sch_lab.so', 'cf/to_lab.so', 'cf/robot_sim.so', 'cf/cf.so', 'cf/rover_app.so']
[generate_juicer_database-1] [INFO] [1709606985.932629795] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/core-cpu1 --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.934332339] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/cfe_assert.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.935778511] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/ci_lab.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.937387039] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/ros_app.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.938911162] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/sample_app.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.940472219] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/sample_lib.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.942001396] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/sbn_f_remap.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.943492982] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/sbn.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.945039602] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/sbn_udp.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.946642380] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/sch_lab.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.948190799] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/to_lab.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.949568540] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/robot_sim.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.951010353] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/cf.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.952519047] [create_message_database]: /root/code/juicer/build/juicer --input /root/code/cFS/build/exe/cpu1/cf/rover_app.so --mode SQLITE --output /root/code/juicer/dbs/combined.sqlite -v4
[generate_juicer_database-1] /bin/sh: 1: /root/code/juicer/build/juicer: not found
[generate_juicer_database-1] [INFO] [1709606985.954002305] [create_message_database]: ===============================================
[generate_juicer_database-1] [INFO] [1709606985.954415655] [create_message_database]: Input files: ['core-cpu1', 'cf/cfe_assert.so', 'cf/ci_lab.so', 'cf/ros_app.so', 'cf/sample_app.so', 'cf/sample_lib.so', 'cf/sbn_f_remap.so', 'cf/sbn.so', 'cf/sbn_udp.so', 'cf/sch_lab.so', 'cf/to_lab.so', 'cf/robot_sim.so', 'cf/cf.so', 'cf/rover_app.so']
[generate_juicer_database-1] [INFO] [1709606985.954855103] [create_message_database]: Generated output file: /root/code/juicer/dbs/combined.sqlite
[generate_juicer_database-1] [INFO] [1709606985.955309346] [create_message_database]: ===============================================
[INFO] [generate_juicer_database-1]: process has finished cleanly [pid 144]
```

However, there's no actual `/root/code/juicer/dbs/combined.sqlite` file being generated:
```
# ls /root/code/juicer/dbs/combined.sqlite
# ls /root/code/juicer/dbs/combined.sqlite
ls: cannot access '/root/code/juicer/dbs/combined.sqlite': No such file or directory
# ls /root/code/juicer/dbs/
#
```

**Comment by ivanperez-keera** [comment]
I used juicer to generate a `combined.sqlite` file and adjusted the `cfe_plugin_config.yaml` accordingly. Now I am seeing:

```
# ros2 launch cfe_plugin cfe_bridge.launch.py
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-03-05-02-58-18-570194-000eb8a29f9e-431
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [fsw_ros2_bridge-1]: process started with pid [432]
[fsw_ros2_bridge-1] [INFO] [1709607499.197213624] [cfe_bridge]: namespace: /groundsystem
[fsw_ros2_bridge-1] [WARN] [1709607499.198452659] [cfe_bridge]: ================================================================
[fsw_ros2_bridge-1] [WARN] [1709607499.200208767] [cfe_bridge]: Using FSW Plugin: cfe_plugin.cfe_plugin
[fsw_ros2_bridge-1] [WARN] [1709607499.202070478] [cfe_bridge]: ================================================================
[fsw_ros2_bridge-1] [INFO] [1709607499.233839630] [cfe_bridge]: Setting up cFE plugin
[fsw_ros2_bridge-1] [WARN] [1709607499.378708991] [cfe_bridge]: Can't replace CFE_ES_CDS_AccessCacheData with CFE_ES_CDS_AccessCache
[fsw_ros2_bridge-1] [WARN] [1709607499.380261452] [cfe_bridge]: wrong size 72 vs 96
[fsw_ros2_bridge-1] [WARN] [1709607499.382781711] [cfe_bridge]: Can't replace CFE_ES_CDS_AccessCacheData with CFE_ES_CDS_AccessCache
[fsw_ros2_bridge-1] [WARN] [1709607499.384467950] [cfe_bridge]: wrong size 72 vs 96
[fsw_ros2_bridge-1] [WARN] [1709607499.509499200] [cfe_bridge]: Can't replace CFE_SB_MsgMapFileEntry_t with CFE_SB_Msg
[fsw_ros2_bridge-1] [WARN] [1709607499.511347771] [cfe_bridge]: wrong size 8 vs 16
[fsw_ros2_bridge-1] [WARN] [1709607499.840415261] [cfe_bridge]: Can't replace CF_ChunkIdx_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709607499.842070089] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709607499.844687113] [cfe_bridge]: Can't replace CF_ChunkIdx_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709607499.846242834] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709607499.848810643] [cfe_bridge]: Can't replace CF_ChunkOffset_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709607499.850366745] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709607499.852985311] [cfe_bridge]: Can't replace CF_ChunkOffset_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709607499.854566314] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709607499.857135525] [cfe_bridge]: Can't replace CF_ChunkSize_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709607499.858756901] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709607499.861399815] [cfe_bridge]: Can't replace CF_ChunkSize_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709607499.862951278] [cfe_bridge]: wrong size 4 vs 8
[fsw_ros2_bridge-1] [WARN] [1709607499.866546159] [cfe_bridge]: Can't replace CF_ChunkList_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709607499.868260880] [cfe_bridge]: wrong size 16 vs 8
[fsw_ros2_bridge-1] [WARN] [1709607499.878243191] [cfe_bridge]: Can't replace CF_Logical_TlvData with CF_Logical_Tlv
[fsw_ros2_bridge-1] [WARN] [1709607499.879883745] [cfe_bridge]: wrong size 8 vs 16
[fsw_ros2_bridge-1] [WARN] [1709607499.882640208] [cfe_bridge]: Can't replace CF_Logical_TlvData with CF_Logical_Tlv
[fsw_ros2_bridge-1] [WARN] [1709607499.884304698] [cfe_bridge]: wrong size 8 vs 16
[fsw_ros2_bridge-1] [WARN] [1709607499.890734841] [cfe_bridge]: Can't replace CF_Logical_TlvList_t with CF_Logical_Tlv
[fsw_ros2_bridge-1] [WARN] [1709607499.892502219] [cfe_bridge]: wrong size 72 vs 16
[fsw_ros2_bridge-1] [WARN] [1709607499.921527581] [cfe_bridge]: Can't replace CF_ChunkWrapper_t with CF_Chunk
[fsw_ros2_bridge-1] [WARN] [1709607499.923269346] [cfe_bridge]: wrong size 32 vs 8
[fsw_ros2_bridge-1] [WARN] [1709607499.981466350] [cfe_bridge]: Can't replace CF_PlaybackDirCmd_t with CF_Playback
[fsw_ros2_bridge-1] [WARN] [1709607499.983608751] [cfe_bridge]: wrong size 144 vs 148
[fsw_ros2_bridge-1] [WARN] [1709607499.986623671] [cfe_bridge]: Can't replace CF_PlaybackDirCmd_t with CF_Playback
[fsw_ros2_bridge-1] [WARN] [1709607499.988608087] [cfe_bridge]: wrong size 144 vs 148
[fsw_ros2_bridge-1] [WARN] [1709607499.991486323] [cfe_bridge]: Can't replace CF_TransactionCmd_t with CF_Transaction
[fsw_ros2_bridge-1] [WARN] [1709607499.993349485] [cfe_bridge]: wrong size 20 vs 136
[fsw_ros2_bridge-1] [INFO] [1709607500.018752584] [cfe_bridge]: udp_receive_port: 1235
[fsw_ros2_bridge-1] [INFO] [1709607500.020738548] [cfe_bridge]: udp_send_port: 1234
[fsw_ros2_bridge-1] [INFO] [1709607500.022635161] [cfe_bridge]: udp_telemetry_ip: 0.0.0.0
[fsw_ros2_bridge-1] [INFO] [1709607500.024540933] [cfe_bridge]: udp_command_ip: 127.0.0.1
[fsw_ros2_bridge-1] [INFO] [1709607500.026198392] [cfe_bridge]: parsing cFE config file...
[fsw_ros2_bridge-1] [INFO] [1709607500.179278774] [cfe_bridge]: commands: 
[fsw_ros2_bridge-1] [INFO] [1709607500.182554333] [cfe_bridge]: telemetry: 
[fsw_ros2_bridge-1] [INFO] [1709607500.184792393] [cfe_bridge]: starting timer thread to receive CFS telemetry
[fsw_ros2_bridge-1] [WARN] [1709607500.187153614] [cfe_bridge]: cmd with msg_size=0 (dynamic)
[fsw_ros2_bridge-1] [WARN] [1709607500.188803421] [cfe_bridge]: cmd with msg_size=0 (dynamic)
[fsw_ros2_bridge-1] Traceback (most recent call last):
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/install/fsw_ros2_bridge/lib/fsw_ros2_bridge/fsw_ros2_bridge", line 33, in <module>
[fsw_ros2_bridge-1]     sys.exit(load_entry_point('fsw-ros2-bridge', 'console_scripts', 'fsw_ros2_bridge')())
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/fsw_ros2_bridge/fsw_ros2_bridge/fsw_ros2_bridge.py", line 419, in main
[fsw_ros2_bridge-1]     bridge = FSWBridge()
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/fsw_ros2_bridge/fsw_ros2_bridge/fsw_ros2_bridge.py", line 72, in __init__
[fsw_ros2_bridge-1]     self._fsw = fsw_ros2_bridge.fsw_wrapper.FSWWrapper(self, self._plugin_name)
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/build/fsw_ros2_bridge/fsw_ros2_bridge/fsw_wrapper.py", line 37, in __init__
[fsw_ros2_bridge-1]     self._plugin = importlib.import_module(plugin, ".").FSWPlugin(node)
[fsw_ros2_bridge-1]   File "/root/code/humble_ws/brash/install/cfe_plugin/local/lib/python3.10/dist-packages/cfe_plugin/cfe_plugin.py", line 152, in __init__
[fsw_ros2_bridge-1]     msg_size = symbol_name_map[ci.get_msg_type()].get_size()
[fsw_ros2_bridge-1] KeyError: 'RoverAppTwistCmdt'
[ERROR] [fsw_ros2_bridge-1]: process has died [pid 432, exit code 1, cmd '/root/code/humble_ws/brash/install/fsw_ros2_bridge/lib/fsw_ros2_bridge/fsw_ros2_bridge --ros-args -r __node:=cfe_bridge --params-file /root/code/humble_ws/brash/install/cfe_plugin/share/cfe_plugin/config/cfe_config.yaml --params-file /root/code/humble_ws/brash/install/juicer_util/share/juicer_util/config/cfe_plugin_config.yaml'].
```

**Comment by ana-GT** [comment]
Hi Ivan, couple of things:

1. The rover reference: Thanks for discovering a buggy commit.  That database was supposed to be part of a branch in cfe_ros2_plugin for a tutorial I am adding today. I didn't realize I inadvertently pushed it to devel, will fix it this morning. Apologies about that one. 
 
2. To explain a bit more: The Rover demo is adding a few new message types, which are expected by the bridge (which is told "what to expect" from a configuration .yaml file). 

Will post a message again here once I delete the reference to the rover and set up the database back to its original.

**Comment by ivanperez-keera** [comment]
Thank you so much, @ana-GT. Looking forward to trying this!

**Comment by ana-GT** [comment]
Hi @ivanperez-keera , so heads-up, fixed the issue and just tested the  tutorials (both using a local setup or the docker setup), so things should work as expected. Thanks for the heads-up.

**Comment by ivanperez-keera** [comment]
I just tried it again. I also tried in docker, but I'm not able to see any data going through. I just sent you an email to discuss separately.

**Comment by ana-GT** [comment]
Mm, not sure what might be going on. We have it running with 4 different users :thinking: .

For reference, since I mentioned it earlier in this Issue, I added a rover demo that runs in docker as well: https://traclabs-brash.bitbucket.io/brash_docker_rover_demo.html

**Comment by ivanperez-keera** [comment]
Ok I'll try that with docker and we can discuss.
